global:
  dataset_path: /dataset-disk/tb_dataset/tf2k_lr/
  # /datasets-disk/tb_dataset/tf2k_lr/ # ok for vm-inter
  # /home/rz/Image-Deepfake-Detectors-Public-Library/truefake_2k
  # vm intern -> /home/rz/TB_WP3/Image-Deepfake-Detectors-Public-Library/truefake_2k/
  device_override: cuda:0  # null for auto-selection
  min_vram: 16000
  split_file: ./test2k_splits.json # ./split.json
  num_threads: 4 #8
  dry_run: false
  only_list: false

 # - 'opencliplinearloranext_clipL14commonpool_r4_qv' # lora version of CLIP
 # - "opencliplinearnext_clipL14commonpool
detector_args:
  - "--arch"
  - "opencliplinearloranext_clipL14commonpool_r4_qv"
  - "--norm_type"
  - "clip"
  - "--resize_size"
  - "200"
  - "--resize_ratio"
  - "1"
  - "--resize_prob"
  - "0.2"
  - "--cmp_qual"
  - "65,100"
  - "--cmp_prob"
  - "0.5"
  - "--resizeSize"
  - "224"

training:
  # - data: gan2:pre&sdXL:pre&realFFHQ:pre&realFORLAB:pre
  # PRESOCIAL
  - data: realFFHQ:pre&realFORLAB:pre&gan1:pre&gan2:pre&gan3:pre&sd15:pre&sd2:pre&sd3:pre&sdXL:pre&flux:pre
  # FACEBOOK
  # - data: realFFHQ:fb&realFORLAB:fb&gan1:fb&gan2:fb&gan3:fb&sd15:fb&sd2:fb&sd3:fb&sdXL:fb&flux:fb
  # # TELEGRAM
  # - data: realFFHQ:tl&realFORLAB:tl&gan1:tl&gan2:tl&gan3:tl&sd15:tl&sd2:tl&sd3:tl&sdXL:tl&flux:tl
  # # TWITTER
  # - data: realFFHQ:tw&realFORLAB:tw&gan1:tw&gan2:tw&gan3:tw&sd15:tw&sd2:tw&sd3:tw&sdXL:tw&flux:tw

testing:
  # # FACEBOOK
  # - realFFHQ:fb
  # - realFORLAB:fb
  # - gan1:fb
  # - gan2:fb
  # - gan3:fb
  # - sd15:fb
  # - sd2:fb
  # - sd3:fb
  # - sdXL:fb
  # - flux:fb
  # TELGRAM
  # - realFFHQ:tl
  # - realFORLAB:tl
  # - gan1:tl
  # - gan2:tl
  # - gan3:tl
  # - sd15:tl
  # - sd2:tl
  # - sd3:tl
  # - sdXL:tl
  # - flux:tl
  # TWITTER
  # - realFFHQ:tw
  # - realFORLAB:tw
  # - gan1:tw
  # - gan2:tw
  # - gan3:tw
  # - sd15:tw
  # - sd2:tw
  # - sd3:tw
  # - sdXL:tw
  # - flux:tw
  # PRESOCIAL
  - realFFHQ:pre
  - realFORLAB:pre
  - gan1:pre
  - gan2:pre
  - gan3:pre
  - sd15:pre
  - sd2:pre
  - sd3:pre
  - sdXL:pre
  - flux:pre

